baseurl = "https://username.github.io"

DefaultContentLanguage = "en"

title = "DART1130 Musings"
theme = "beautifulhugo"

metaDataFormat = "yaml"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

googleAnalytics = "UA-107434487-2"

[Params]
  subtitle = "Musings of a DART1130 student"
  mainSections = ["post","posts"]
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true

[Author]
  name = "Andrew Wong (z5206677)"
  website = "featherbear"
  email = "z5206677@student.unsw.edu.au"
  facebook = "andrewjinmengwong"
  github = "featherbear"
  linkedin = "andrewjinmengwong"
  instagram = "_andrewjwong"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Works"
    url = "/post/portfolio"
    weight = 2

[[menu.main]]
    name = "Adventure Log"
    url = "/post/adventure-log"
    weight = 3
